# Generated by Django 5.2.8 on 2025-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
