# Generated by Django 5.2.8 on 2025-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="nickname",
        ),
        migrations.AddField(
            model_name="customuser",
            name="nnickname",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
