"""
Django settings for final project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# # [디버깅 코드 시작] --------------------------------
# env_path = os.path.join(BASE_DIR, '.env')
# print(f"👉 .env 파일 경로: {env_path}")
# print(f"👉 파일이 실제로 존재하는가? {os.path.exists(env_path)}")
# # [디버깅 코드 끝] ----------------------------------

# load_dotenv(env_path)

# KAKAO_MAP_JS_KEY = os.getenv("KAKAO_MAP_JS_KEY")
# print(f"👉 불러온 키 값: {KAKAO_MAP_JS_KEY}") # 키가 None이면 실패한 것

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wj5_vx%vo&7dx+5l4^f5uk=-mx+gel*9b$a*4kagx(d*(xlb73'

load_dotenv(os.path.join(BASE_DIR, '.env'))
KAKAO_MAP_JS_KEY = os.getenv("KAKAO_MAP_JS_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',  # 사용자 관련 앱 e06 추가
    'posts',  # 금융 게시판 앱 pjt06 추가
    'finances',  # 금융 상품 관련 앱 pjt06 추가
    'notices', # 공지사항 앱
    'banks',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   #  프로젝트 공통 템플릿 폴더
        'APP_DIRS': True,                   #  각 앱 내부 templates 도 자동 탐색
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # request 사용 가능
                'django.contrib.auth.context_processors.auth', # user, perms 사용 가능
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'final.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',   #  project-level static
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'accounts:login'                 # 로그인 필요할 때 이동할 URL name
LOGIN_REDIRECT_URL = '/'        # 로그인 성공 후
LOGOUT_REDIRECT_URL = '/'       # 로그아웃 후

AUTH_USER_MODEL = 'accounts.CustomUser'

