# Generated by Django 5.2.8 on 2025-12-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('inquiry', '1:1 문의'), ('free', '자유게시판'), ('review', '상품후기'), ('qna', 'Q&A'), ('tips', '투자꿀팁'), ('faq', 'FAQ')], default='free', max_length=20),
        ),
    ]
