# Generated by Django 5.2.8 on 2025-12-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_nickname_customuser_nnickname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="nnickname",
            new_name="nickname",
        ),
    ]
