# Generated by Django 5.2.8 on 2025-12-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('BANK', '은행'), ('SECURITIES', '증권사'), ('ATM', 'ATM'), ('OTHER', '기타')], default='BANK', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('org_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
