# Generated by Django 5.2.8 on 2025-12-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='financial_products',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', to='finlife.depositoptions'),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_appetite',
            field=models.IntegerField(choices=[(1, '안정형'), (2, '안정추구형'), (3, '위험중립형'), (4, '적극투자형'), (5, '공격투자형')], default=3),
        ),
    ]
