# Generated by Django 5.2.9 on 2025-12-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_financial_products_user_risk_appetite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='financial_products',
        ),
    ]
