# Generated by Django 5.2.8 on 2025-12-12 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=50)),
                ('cur_nm', models.CharField(max_length=50)),
                ('ttb', models.CharField(max_length=50)),
                ('tts', models.CharField(max_length=50)),
                ('deal_bas_r', models.CharField(max_length=50)),
                ('bkpr', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('interest_rate', models.FloatField()),
                ('highest_rate', models.FloatField(blank=True, null=True)),
                ('join_term', models.CharField(blank=True, max_length=50)),
                ('link_url', models.URLField(blank=True)),
                ('rank_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_user', models.ManyToManyField(blank=True, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('interest_rate', models.FloatField()),
                ('highest_rate', models.FloatField(blank=True, null=True)),
                ('join_term', models.CharField(blank=True, max_length=50)),
                ('link_url', models.URLField(blank=True)),
                ('rank_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_user', models.ManyToManyField(blank=True, related_name='savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
